name: create_report_card
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.6.0
  dart_appwrite: ^21.1.0
  dart_openai: ^6.1.1
  gradebee_models:
    path: ../gradebee-models
  gradebee_function_helpers:
    path: ../gradebee-function-helpers
  dotenv: ^4.1.0

dev_dependencies:
  dotenv: ^4.2.0
  lints: ^5.0.0
  test: ^1.24.0
  mockito: ^5.4.0
  build_runner: ^2.4.0
