name: transcribe_note
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  # pinned to 12.1.0 because of https://github.com/appwrite/sdk-for-dart/issues/68
  dart_appwrite: ^21.1.0
  dart_openai: ^6.1.1
  gradebee_models:
    path: ../gradebee-models

dev_dependencies:
  dotenv: ^4.2.0
  lints: ^5.0.0
  test: ^1.25.14
